### PR TITLE
Fix README + More Consistent with Badger

### PR DESCRIPTION
**Pull request by Wolveix**
- Changed the `DefaultOptions` variable to a function to more closely resemble Badger
- Fixed the incorrect example at the bottom of the README

The `DefaultOptions` change is technically a breaking change, but I think it helps to bring the functionality closer to Badger's own.

### CODE REVIEW

**Comment by timshannon** [comment]
So I chose that API specifically cause it matches the API in [BoltHold](https://github.com/timshannon/bolthold), which came first and whose interface was inspired by [Bolt](https://github.com/etcd-io/bbolt).  I specifically chose that so that bolthold and badgerhold could be swapped out fairly easily (https://tech.townsourced.com/post/boltdb-vs-badger/#summary).

The idea being that Badger and Bolt both have different use cases and excel better in different situations, but you don't always know that when starting a project.  Using something like Bolthold/BadgerHold allows you easily switch between the two if needed.

**Comment by Wolveix** [comment]
Yeah I figured as much, that makes sense. But the example in the README didn't work, which was the original reason for the PR. I'm happy to revert the `DefaultOptions` change though!

**Comment by timshannon** [comment]
Sure go for it, and I'll merge your PR.

Thanks!

**Comment by Wolveix** [comment]
@timshannon Thanks! I just made an additional commit as I forgot to revert the README to the original `DefaultOptions`, looks like it was a minute too late though. Want me to open another PR for it?

**Comment by timshannon** [comment]
Sure.

**Pull request merged**
